### ISSUE TITLE
iOS编译失败

### ISSUE THREAD

**Issue by SiriDx** [rongcloud/imkit-flutter-quickstart#2]
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[RCPublicServiceWebViewController viewDidLoad] in RongIMLib(RCPublicServiceWebViewController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CNHarrySun** [comment]
你好，请按照下面步骤更新一下。
初次安装需要从 pod 下载 IMLib 的 iOS SDK，要花费较长的时间，建议手动更新一下

Podfile 目录执行 pod repo update 命令
Podfile 目录执行 pod update 命令
